/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ditado;

import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javazoom.jl.decoder.JavaLayerException;


/**
 *
 * @author danillo
 */
public class Janela extends javax.swing.JFrame {

    int indice = 1;
    Audio audio = new Audio("audio" + indice + ".mp3");
    int inicio = 0;
    /*230frames aproximadamente 5s*/
    private static final int QNTD_FRAMES = 230;
    int fim = QNTD_FRAMES; 
    String palavra = "";
    String textoLido = "";
    Texto texto = new Texto("texto" + indice + ".txt");

    /**
     * Creates new form Tocador
     */
    public Janela() {
        initComponents();
        try {
            tituloDoTexto.setText("Ditado: " + texto.pegaTitulo());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playBotao = new javax.swing.JButton();
        tituloDoTexto = new javax.swing.JLabel();
        botaoOk = new javax.swing.JButton();
        campoDeTexto = new javax.swing.JTextField();
        avancarBotao = new javax.swing.JButton();
        retrocederBotao = new javax.swing.JButton();
        proximoBotao = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaDeTexto = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playBotao.setText(">");
        playBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBotaoActionPerformed(evt);
            }
        });

        tituloDoTexto.setText("Ditado:");

        botaoOk.setText("OK");
        botaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOkActionPerformed(evt);
            }
        });

        campoDeTexto.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        campoDeTexto.setText("Digite aqui...");
        campoDeTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoDeTextoKeyPressed(evt);
            }
        });

        avancarBotao.setText(">>");
        avancarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancarBotaoActionPerformed(evt);
            }
        });

        retrocederBotao.setText("<<");
        retrocederBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrocederBotaoActionPerformed(evt);
            }
        });

        proximoBotao.setText("Próximo Texto");
        proximoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoBotaoActionPerformed(evt);
            }
        });

        areaDeTexto.setEditable(false);
        jScrollPane2.setViewportView(areaDeTexto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoDeTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(playBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(retrocederBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avancarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(proximoBotao))
                            .addComponent(tituloDoTexto))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloDoTexto)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playBotao)
                    .addComponent(avancarBotao)
                    .addComponent(retrocederBotao)
                    .addComponent(proximoBotao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoOk))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBotaoActionPerformed
        try {
            audio.play(inicio, fim);
        } catch (FileNotFoundException | JavaLayerException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_playBotaoActionPerformed

    private void botaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOkActionPerformed
        try {
            palavra = campoDeTexto.getText();

            palavra = texto.comparaPalavra(palavra);
            if (!palavra.equals("#FIM#")) {

                if (palavra.contains("#")) {
                    areaDeTexto.setText(textoLido + palavra);

                } else {
                    textoLido += palavra;
                    areaDeTexto.setText(textoLido);
                    textoLido += " ";
                    campoDeTexto.setText("");
                }
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_botaoOkActionPerformed

    private void campoDeTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDeTextoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                palavra = campoDeTexto.getText();

                palavra = texto.comparaPalavra(palavra);
                if (!palavra.equals("#FIM#")) {

                    if (palavra.contains("#")) {
                        areaDeTexto.setText(textoLido + palavra);

                    } else {
                        textoLido += palavra;
                        areaDeTexto.setText(textoLido);
                        textoLido += " ";
                        campoDeTexto.setText("");
                    }
                }

            } catch (FileNotFoundException ex) {
                Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_campoDeTextoKeyPressed

    private void avancarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancarBotaoActionPerformed
        inicio += QNTD_FRAMES;
        fim += QNTD_FRAMES;

        try {
            audio.stop();
            audio.play(inicio, fim);
        } catch (FileNotFoundException | JavaLayerException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_avancarBotaoActionPerformed
 
    
    private void retrocederBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrocederBotaoActionPerformed
        inicio -= QNTD_FRAMES;
        fim -= QNTD_FRAMES;
        if (inicio < 0) {
            inicio = 0;
            fim = QNTD_FRAMES;
        }
        try {
            audio.stop();
            audio.play(inicio, fim);
        } catch (FileNotFoundException | JavaLayerException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_retrocederBotaoActionPerformed

    private void proximoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoBotaoActionPerformed
        indice += 1;
        audio.setNomeDoArquivo("audio" + indice + ".mp3");
        texto.setNomeDoArquivo("texto" + indice + ".txt");
        areaDeTexto.setText("");
        inicio = 0;
        fim = QNTD_FRAMES;
        try {
            tituloDoTexto.setText("Ditado: " + texto.pegaTitulo());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_proximoBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane areaDeTexto;
    private javax.swing.JButton avancarBotao;
    private javax.swing.JButton botaoOk;
    private javax.swing.JTextField campoDeTexto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton playBotao;
    private javax.swing.JButton proximoBotao;
    private javax.swing.JButton retrocederBotao;
    private javax.swing.JLabel tituloDoTexto;
    // End of variables declaration//GEN-END:variables
}
